# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/configuredialog.ui'
#
# Created: Fri Jul 15 14:22:18 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ConfigureDialog(object):
    def setupUi(self, ConfigureDialog):
        ConfigureDialog.setObjectName("ConfigureDialog")
        ConfigureDialog.resize(550, 303)
        self.gridLayout = QtGui.QGridLayout(ConfigureDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.configGroupBox = QtGui.QGroupBox(ConfigureDialog)
        self.configGroupBox.setTitle("")
        self.configGroupBox.setObjectName("configGroupBox")
        self.formLayout = QtGui.QFormLayout(self.configGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label0 = QtGui.QLabel(self.configGroupBox)
        self.label0.setObjectName("label0")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label0)
        self.lineEdit0 = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit0.setObjectName("lineEdit0")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit0)
        self.label2 = QtGui.QLabel(self.configGroupBox)
        self.label2.setObjectName("label2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label2)
        self.comboBox_in_unit = QtGui.QComboBox(self.configGroupBox)
        self.comboBox_in_unit.setObjectName("comboBox_in_unit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBox_in_unit)
        self.label3 = QtGui.QLabel(self.configGroupBox)
        self.label3.setObjectName("label3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label3)
        self.comboBox_out_unit = QtGui.QComboBox(self.configGroupBox)
        self.comboBox_out_unit.setObjectName("comboBox_out_unit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox_out_unit)
        self.label4 = QtGui.QLabel(self.configGroupBox)
        self.label4.setObjectName("label4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label4)
        self.checkBox_write_osim_file = QtGui.QCheckBox(self.configGroupBox)
        self.checkBox_write_osim_file.setText("")
        self.checkBox_write_osim_file.setObjectName("checkBox_write_osim_file")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.checkBox_write_osim_file)
        self.label = QtGui.QLabel(self.configGroupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label)
        self.checkBox_static_vas = QtGui.QCheckBox(self.configGroupBox)
        self.checkBox_static_vas.setText("")
        self.checkBox_static_vas.setObjectName("checkBox_static_vas")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.checkBox_static_vas)
        self.label1 = QtGui.QLabel(self.configGroupBox)
        self.label1.setObjectName("label1")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_osim_output_dir = QtGui.QLineEdit(self.configGroupBox)
        self.lineEdit_osim_output_dir.setObjectName("lineEdit_osim_output_dir")
        self.horizontalLayout.addWidget(self.lineEdit_osim_output_dir)
        self.pushButton_osim_output_dir = QtGui.QPushButton(self.configGroupBox)
        self.pushButton_osim_output_dir.setObjectName("pushButton_osim_output_dir")
        self.horizontalLayout.addWidget(self.pushButton_osim_output_dir)
        self.formLayout.setLayout(6, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_2 = QtGui.QLabel(self.configGroupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_2)
        self.checkBox_update_knee_splines = QtGui.QCheckBox(self.configGroupBox)
        self.checkBox_update_knee_splines.setText("")
        self.checkBox_update_knee_splines.setObjectName("checkBox_update_knee_splines")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.checkBox_update_knee_splines)
        self.gridLayout.addWidget(self.configGroupBox, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ConfigureDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(ConfigureDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ConfigureDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ConfigureDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigureDialog)
        ConfigureDialog.setTabOrder(self.lineEdit0, self.comboBox_in_unit)
        ConfigureDialog.setTabOrder(self.comboBox_in_unit, self.comboBox_out_unit)
        ConfigureDialog.setTabOrder(self.comboBox_out_unit, self.checkBox_write_osim_file)
        ConfigureDialog.setTabOrder(self.checkBox_write_osim_file, self.checkBox_static_vas)
        ConfigureDialog.setTabOrder(self.checkBox_static_vas, self.lineEdit_osim_output_dir)
        ConfigureDialog.setTabOrder(self.lineEdit_osim_output_dir, self.pushButton_osim_output_dir)
        ConfigureDialog.setTabOrder(self.pushButton_osim_output_dir, self.buttonBox)

    def retranslateUi(self, ConfigureDialog):
        ConfigureDialog.setWindowTitle(QtGui.QApplication.translate("ConfigureDialog", "Configure Fieldwork Gait2392 Muscle HMF Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label0.setText(QtGui.QApplication.translate("ConfigureDialog", "identifier:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label2.setText(QtGui.QApplication.translate("ConfigureDialog", "Input unit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label3.setText(QtGui.QApplication.translate("ConfigureDialog", "Output unit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label4.setText(QtGui.QApplication.translate("ConfigureDialog", "Write Osim file:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ConfigureDialog", "Static Vastus:", None, QtGui.QApplication.UnicodeUTF8))
        self.label1.setText(QtGui.QApplication.translate("ConfigureDialog", "Output folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_osim_output_dir.setText(QtGui.QApplication.translate("ConfigureDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ConfigureDialog", "Update Knee Splines:", None, QtGui.QApplication.UnicodeUTF8))

